-- Three layers:
--   raw   one table per source entity, append-only, every row tagged with its batch
--   mart  star schema for analytics (surrogate keys, SCD type 1 dimensions)
--   meta  run log with per-stage timings and reconciliation results

CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS mart;
CREATE SCHEMA IF NOT EXISTS meta;

-- raw ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS raw.customers (
    customer_id  bigint      NOT NULL,
    full_name    text,
    email        text,
    state        text,
    signup_at    timestamptz,
    _batch_id    text        NOT NULL,
    _loaded_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS raw.products (
    product_id   bigint      NOT NULL,
    sku          text,
    name         text,
    category     text,
    brand        text,
    price_cents  bigint,
    cost_cents   bigint,
    active       boolean,
    _batch_id    text        NOT NULL,
    _loaded_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS raw.orders (
    order_id        bigint      NOT NULL,
    customer_id     bigint,
    ordered_at      timestamptz,
    status          text,
    channel         text,
    subtotal_cents  bigint,
    discount_cents  bigint,
    shipping_cents  bigint,
    total_cents     bigint,
    delivered_at    timestamptz,
    _batch_id       text        NOT NULL,
    _loaded_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS raw.order_items (
    order_item_id     bigint      NOT NULL,
    order_id          bigint,
    product_id        bigint,
    quantity          bigint,
    unit_price_cents  bigint,
    line_total_cents  bigint,
    _batch_id         text        NOT NULL,
    _loaded_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS raw.payments (
    payment_id    bigint      NOT NULL,
    order_id      bigint,
    method        text,
    installments  smallint,
    status        text,
    amount_cents  bigint,
    paid_at       timestamptz,
    _batch_id     text        NOT NULL,
    _loaded_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS customers_batch_idx   ON raw.customers   (_batch_id);
CREATE INDEX IF NOT EXISTS products_batch_idx    ON raw.products    (_batch_id);
CREATE INDEX IF NOT EXISTS orders_batch_idx      ON raw.orders      (_batch_id);
CREATE INDEX IF NOT EXISTS order_items_batch_idx ON raw.order_items (_batch_id);
CREATE INDEX IF NOT EXISTS payments_batch_idx    ON raw.payments    (_batch_id);

-- mart --------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS mart.dim_date (
    date_key     integer  PRIMARY KEY,          -- yyyymmdd
    full_date    date     NOT NULL UNIQUE,
    year         smallint NOT NULL,
    quarter      smallint NOT NULL,
    month        smallint NOT NULL,
    day          smallint NOT NULL,
    iso_weekday  smallint NOT NULL,             -- 1 = Monday
    is_weekend   boolean  NOT NULL
);

CREATE TABLE IF NOT EXISTS mart.dim_customer (
    customer_key  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   bigint NOT NULL UNIQUE,
    full_name     text,
    email         text,
    state         text,
    signup_at     timestamptz,
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS mart.dim_product (
    product_key  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   bigint NOT NULL UNIQUE,
    sku          text,
    name         text,
    category     text,
    brand        text,
    price_cents  bigint,
    cost_cents   bigint,
    active       boolean,
    updated_at   timestamptz NOT NULL DEFAULT now()
);

-- "Unknown" members: a fact whose customer or product is missing still loads,
-- pointing at key -1, instead of being dropped or failing the whole batch.
INSERT INTO mart.dim_customer (customer_key, customer_id, full_name)
VALUES (-1, -1, 'Unknown') ON CONFLICT DO NOTHING;
INSERT INTO mart.dim_product (product_key, product_id, name)
VALUES (-1, -1, 'Unknown') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS mart.fact_orders (
    order_id         bigint  PRIMARY KEY,
    date_key         integer NOT NULL REFERENCES mart.dim_date,
    customer_key     bigint  NOT NULL REFERENCES mart.dim_customer,
    status           text    NOT NULL,
    channel          text,
    item_count       integer NOT NULL,
    subtotal_cents   bigint  NOT NULL,
    discount_cents   bigint  NOT NULL,
    shipping_cents   bigint  NOT NULL,
    total_cents      bigint  NOT NULL,
    payment_method   text,
    payment_status   text,
    installments     smallint,
    ordered_at       timestamptz NOT NULL,
    paid_at          timestamptz,
    delivered_at     timestamptz,
    delivery_days    numeric(6, 2),
    _batch_id        text    NOT NULL
);

CREATE TABLE IF NOT EXISTS mart.fact_order_items (
    order_item_id       bigint  PRIMARY KEY,
    order_id            bigint  NOT NULL,
    date_key            integer NOT NULL REFERENCES mart.dim_date,
    customer_key        bigint  NOT NULL REFERENCES mart.dim_customer,
    product_key         bigint  NOT NULL REFERENCES mart.dim_product,
    quantity            bigint  NOT NULL,
    unit_price_cents    bigint  NOT NULL,
    line_total_cents    bigint  NOT NULL,
    line_cost_cents     bigint  NOT NULL,
    gross_margin_cents  bigint  NOT NULL,
    _batch_id           text    NOT NULL
);

CREATE INDEX IF NOT EXISTS fact_orders_date_idx       ON mart.fact_orders (date_key);
CREATE INDEX IF NOT EXISTS fact_orders_customer_idx   ON mart.fact_orders (customer_key);
CREATE INDEX IF NOT EXISTS fact_items_date_idx        ON mart.fact_order_items (date_key);
CREATE INDEX IF NOT EXISTS fact_items_product_idx     ON mart.fact_order_items (product_key);

-- meta --------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS meta.pipeline_runs (
    run_id       bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    batch_id     text        NOT NULL,
    load_method  text        NOT NULL,
    status       text        NOT NULL,          -- running, success, failed
    started_at   timestamptz NOT NULL DEFAULT now(),
    finished_at  timestamptz,
    stage_seconds jsonb,
    row_counts   jsonb,
    checks       jsonb,
    error        text
);
